name: Sync Leetcode Past Progress
on:
  workflow_dispatch: # Allows you to run this manually whenever you want
  schedule:
    - cron: "0 8 * * 6" # Automatically double-checks for updates every Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sync Script
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          commit-header: '[LeetCode Sync History]'
