name: Sync Leetcode Past Progress
on:
  workflow_dispatch: # Allows manual trigger anytime
  schedule:
    - cron: "0 * * * *" # Runs automatically at minute 0 of every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Sync Script
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
